import { test, expect } from '@playwright/test';

test('sharing protocol selectors align, update access choices and fit the viewport', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: '共享中心', exact: true }).click();
  const protocol = page.getByRole('button', { name: '共享协议', exact: true });
  const access = page.getByRole('button', { name: '共享访问模式', exact: true });
  await protocol.scrollIntoViewIfNeeded();
  const protocolBox = (await protocol.boundingBox())!;
  const accessBox = (await access.boundingBox())!;
  expect(protocolBox.height).toBe(accessBox.height);
  expect(protocolBox.width).toBeCloseTo(accessBox.width, 0);
  expect(protocolBox.x).toBeGreaterThan(accessBox.x);
  await protocol.click();
  await page.getByRole('option', { name: 'WebDAV', exact: true }).click();
  await expect(access).toHaveText('密码访问');
  await access.click();
  await expect(page.getByRole('option', { name: '仅信任 Node' })).toHaveCount(0);
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 800, height: 480 });
  await protocol.scrollIntoViewIfNeeded();
  await protocol.click();
  const menu = page.getByRole('listbox', { name: '共享协议', exact: true });
  const box = (await menu.boundingBox())!;
  expect(box.y).toBeGreaterThanOrEqual(0);
  expect(box.y + box.height).toBeLessThanOrEqual(480);
  await page.getByRole('option', { name: 'SMB', exact: true }).click();
  await expect(page.getByRole('spinbutton', { name: '监听端口，0为自动分配' })).toHaveValue('445');
  await expect(page.getByText('该协议使用系统或第三方服务的访问控制', { exact: false })).toHaveCount(0);
});
